### PR TITLE
Dev gir

### PR DESCRIPTION
**Pull request by AcostArichA**
My system is Rosinka 2013 → Linux Mint 15 Olivia →Ubuntu 13.04 Raring Ringtail.
Hi! I cannot  run the caja-terminal program by Linux Mint 15 Olivia Mate  Russian fork Rosinka having caja 1.6.0. 
About README file.
I cannot undastand what it means "for MATE-1.6.0, don't use python-caja-1.6.0" ?
 I do have Mate 1.6.0 and My repositories have exactly  python-caja-1.6.0. 
And what I must to do with "...don't use python-caja-1.6.0" ? 
  These addreses inside the file such as
 PyGTK 2.x <http://pygtk.org/>
 Caja Python <http://pub.mate-desktop.org/releases/1.4/python-caja>
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/patches/python-caja_removal_of_mate-python_usage.patch
doesn't work at all, "Not found".
I would be very pleased to recieve your support to install and sucsessfully  run such a beauteful applet CAJA-TERMINAL.
Thank YOU very much!

### CODE REVIEW

**Comment by NiceandGently** [comment]
The port to gobject-introspection isn't finished, here i need a bit help.
But you can use caja-terminal with python-caja-1.4.x for the momment.
This is how i handle it in fedora.

**Comment by AcostArichA** [comment]
Thanks. I have been installed python-caja-1.4.0 .deb package from http://www.ubuntuupdates.org/package/mint_import/nadia/import/base/python-caja . But after I unpacked it and reloaded my system the  Caja coldn't download at all. Black screen on my Desktop, invisible directories etc. I removed it and all is nice.

**Comment by NiceandGently** [comment]
sorry, i don't know anything about package situation in linuxmint,....i'm fedora maintainer.
Maybe ask for help for downgrage python-caja in mint forum or mint irc chanels.
But i hope to get gir port working in near future.

**Comment by AcostArichA** [comment]
Thank You!

**Pull request closed without merging**
